name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Python einrichten
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Caches einrichten
        uses: actions/cache@v6
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}

      - name: PlatformIO installieren
        run: pip install platformio

      - name: Projekt bauen
        run: pio run